[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port 8000"
# Sin healthcheck por ahora, para verificar que funciona
# healthcheckPath = "/health"
# healthcheckTimeout = 30
restartPolicyType = "on_failure"
